# Generated by Django 3.0.8 on 2020-09-08 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200803_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='users_watching',
            field=models.ManyToManyField(blank=True, related_name='watchlisted', to=settings.AUTH_USER_MODEL),
        ),
    ]
