# Generated by Django 3.0.8 on 2020-10-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200915_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='link',
            new_name='image',
        ),
    ]
